apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data
  namespace: broker
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/kafka"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-connect-data
  namespace: broker
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"