apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data
  namespace: metric
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/prometheus"