apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data
  namespace: broker
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/zookeeper/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log
  namespace: broker
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/zookeeper/log"