apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      volumes:
        - name: kafka-connect-data
          persistentVolumeClaim:
            claimName: kafka-connect-data-claim
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:latest
          ports:
            - containerPort: 8083
          command: 
            - bash
            - -c
            - |
              echo "Launching Kafka Connect worker"
              /etc/confluent/docker/run
              #
              echo "Waiting for Kafka Connect to start listening on http://$CONNECT_REST_ADVERTISED_HOST_NAME:$CONNECT_REST_PORT/connectors â³"
              while [ $(curl -s -o /dev/null -w %{http_code} http://$CONNECT_REST_ADVERTISED_HOST_NAME:$CONNECT_REST_PORT/connectors) -ne 200 ] ; do 
                echo -e $(date) " Kafka Connect listener HTTP state: " $(curl -s -o /dev/null -w %{http_code} http://$CONNECT_REST_ADVERTISED_HOST_NAME:$CONNECT_REST_PORT/connectors) " (waiting for 200)"
                sleep 5 
              done
              nc -vz $CONNECT_REST_ADVERTISED_HOST_NAME $CONNECT_REST_PORT
              echo -e "\n--\n+> Creating Kafka Connect MongoDB sink Current PATH ($PWD)"
              /data/scripts/create_mongo_sink.sh 
              echo -e "\n--\n+> Creating MQTT Source Connect Current PATH ($PWD)"
              /data/scripts/create_mqtt_source.sh
              #echo -e "\n--\n+> Creating Kafka Connect Prometheus sink Current PATH ($PWD)"
              #/data/scripts/create_prometheus_sink.sh
              sleep infinity
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "http://kafka:9092"
            - name: CONNECT_GROUP_ID
              value: "kafka-connect-group"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "kafka-connect-meta-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "kafka-connect-meta-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "kafka-connect-meta-status"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: "kafka-connect"
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java,/data/connectors/"
            - name: CONNECT_LOG4J_ROOT_LOGLEVEL
              value: "INFO"
          volumeMounts:
            - name: kafka-connect-data
              mountPath: /data