apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-rest-proxy
  namespace: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-rest-proxy
  template:
    metadata:
      labels:
        app: kafka-rest-proxy
    spec:
      containers:
        - name: kafka-rest-proxy
          image: confluentinc/cp-kafka-rest:latest
          ports:
            - containerPort: 8082
          env:
            - name: KAFKA_REST_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_REST_LISTENERS
              value: "http://0.0.0.0:8082/"
            - name: KAFKA_REST_HOST_NAME
              value: "kafka-rest-proxy"
            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              value: "kafka:9092"