apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topics-ui
  namespace: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-topics-ui
  template:
    metadata:
      labels:
        app: kafka-topics-ui
    spec:
      containers:
        - name: kafka-topics-ui
          image: landoop/kafka-topics-ui:latest
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_REST_PROXY_URL
              value: "http://kafka-rest-proxy:8082/"
            - name: PROXY
              value: "true"