apiVersion: apps/v1
kind: Deployment
metadata:
  name: cistern-server
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cistern-server
  template:
    metadata:
      labels:
        app: cistern-server
    spec:
      containers:
      - name: cistern-server
        image: alejandro945/server-cisterns:latest
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: 4000
        - name: MONGO_URI
          value: mongodb://main_admin:admin@mongodb-service.apps.svc.cluster.local:27017/cisterns?authSource=admin&ssl=false
        - name: KAFKA_BROKER
          value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092