apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: apps
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: main_admin
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: admin
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongodb-service.apps.svc.cluster.local 
          - name: ME_CONFIG_MONGODB_AUTH_DATABASE
            value: admin
          - name: ME_CONFIG_MONGODB_AUTH_USERNAME
            value: main_admin
          - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
            value: admin
          - name: ME_CONFIG_BASICAUTH_USERNAME
            value: admin
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: apps
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081