apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mo-data-pvc
  namespace: apps
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi