apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: broker
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-rest-proxy
  namespace: broker
spec:
  selector:
    app: kafka-rest-proxy
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-topics-ui
  namespace: broker
spec:
  selector:
    app: kafka-topics-ui
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: broker
spec:
  selector:
    app: kafka-connect
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-ui
  namespace: broker
spec:
  selector:
    app: kafka-connect-ui
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000