apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: metric
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: nodeexporter
  namespace: metric
spec:
  selector:
    app: nodeexporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100