apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest-ubuntu
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/datasources
            - name: grafana-dashboards
              mountPath: /etc/grafana/dashboards
            - name: grafana-setup
              mountPath: /setup.sh
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-password
            - name: GF_INSTALL_PLUGINS
              value: "grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: prometheus-data
        - name: grafana-datasources
          hostPath:
            path: /path/to/grafana/datasources
        - name: grafana-dashboards
          hostPath:
            path: /path/to/grafana/dashboards
        - name: grafana-setup
          hostPath:
            path: /path/to/setup.sh