apiVersion: apps/v1
kind: Deployment
metadata:
  name: cistern-app
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cistern-app
  template:
    metadata:
      labels:
        app: cistern-app
    spec:
      containers:
      - name: cistern-app
        image: alejandro945/app-cisterns:latest
        ports:
        - containerPort: 3000
        env:
          MONGO_URI: "mongodb://admin:admin@mongodb-service:27017/cisterns"
---
apiVersion: v1
kind: Service
metadata:
  name: cistern-service
  namespace: apps
spec:
  selector:
    app: cistern-app
  ports:
  - name: http
    port: 80
    targetPort: 3000